# Generated by Django 5.0 on 2024-01-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acc_type',
            field=models.CharField(choices=[('full', 'All courses'), ('free', 'Free courses')], default='free', max_length=30),
        ),
    ]
