# Generated by Django 5.0 on 2023-12-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Uniq course name')),
                ('title', models.CharField(max_length=120, verbose_name='Course name')),
                ('desc', models.TextField(verbose_name='Course description')),
                ('image', models.ImageField(default='default.png', upload_to='course_images', verbose_name='Image for course')),
            ],
        ),
    ]
