# Generated by Django 5.0 on 2024-01-03 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Uniq lesson name')),
                ('title', models.CharField(max_length=120, verbose_name='Lesson name')),
                ('desc', models.TextField(verbose_name='Lesson description')),
                ('number', models.IntegerField(verbose_name='Lesson number')),
                ('video_url', models.CharField(max_length=100, verbose_name='Video URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Which course?')),
            ],
        ),
    ]
