# Generated by Django 5.0 on 2024-01-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_leson_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Free course?'),
        ),
    ]
