# Generated by Django 5.0 on 2024-01-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='free',
        ),
        migrations.AddField(
            model_name='course',
            name='free',
            field=models.BooleanField(default=True, verbose_name='Free course?'),
        ),
    ]
